class SlackRouter < Formula
  desc "Route Slack slash-commands with a cron-like approach"
  homepage "https://github.com/nlink-jp/slack-router"
  url "https://github.com/nlink-jp/slack-router/releases/download/v0.3.0/slack-router-v0.3.0-darwin-arm64.zip"
  version "0.3.0"
  sha256 "2c53d91c133ae4c3a7aed9931280a6fca87fa7dfa4487124d7e682a8777dc793"
  license "MIT"

  # Prebuilt, Developer ID signed + Apple-notarized Apple Silicon binary.
  # Unlike the other formulae, slack-router's release zip wraps its payload in a
  # versioned directory (binary + docs + example config), so this formula is
  # hand-maintained rather than generated by scripts/gen-brew.sh.
  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install Dir["slack-router-*/slack-router"].first
    prefix.install Dir["slack-router-*/config.example.yaml"].first if Dir["slack-router-*/config.example.yaml"].any?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slack-router --version")
  end
end
